version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name
      - name: last_name
        description: Customer's last name
      - name: email
        description: Customer's email
      - name: phone
        description: Customer's phone
      - name: birth_date
        description: Customer's birth date
      - name: regular
        description: This is an identifier if the customer is regular
  - name: stg_employees
    columns:
      - name: employee_id
        description: This is a unique identifier for an employee
        tests:
          - unique
          - not_null
      - name: first_name
        description: Employee's first name
      - name: last_name
        description: Employee's first name
      - name: email
        description: Employee's email
      - name: phone
        description: Employee's phone
      - name: position
        description: Employee's position
  - name: stg_books
    columns:
      - name: book_id
        description: This is a unique identifier for a book
        tests:
          - unique
          - not_null
      - name: book_title
        description: Book's title
      - name: book_genre
        description: Book's genre
        tests:
          - accepted_values:
              values: ['Dystopian', 'Fantasy', 'Science Fiction', 'Non-Fiction', 'Mystery']
      - name: book_price
        description: Book's price
        tests:
          - not_null
      - name: book_isbn
        description: Book's isbn
      - name: book_publication_year
        description: Book's publication year
  - name: stg_bookorders
    columns:
      - name: order_id
        description: This is a unique identifier for an order
      - name: book_id
        description: Foreign key to the books table
      - name: customer_id
        description: Foreign key to the customers table
      - name: handled_by
        description: Foreign key to the employees table
      - name: order_date
        description: Date that the order was placed
      - name: status
        description: This is current status of an order
        tests:
          - accepted_values:
              values: ['Completed', 'Pending', 'Cancelled']
  - name: stg_authors
    columns:
      - name: author_id
        description: This is a unique identifier for an author
      - name: author_first_name
        description: Author's first name
      - name: author_last_name
        description: Author's last name
      - name: author_biography
        description: Author's biography
